name: Feature Request
description: Suggest a feature for DNSChat
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the feature you'd like to see.
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use case
      description: Explain the problem this feature would solve or the workflow it would improve.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or workarounds you've considered.
    validations:
      required: false
